<?xml version="1.0"?>
<robot name="$(arg ARM)_$(arg R_EE)_flobi"
     xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find agni_description)/robots/$(arg ARM)_$(arg R_EE).urdf.xacro" /> 
  <xacro:include filename="$(find agni_description)/$(arg ARM)/$(arg ARM)_includes.urdf.xacro" />   
  <xacro:include filename="$(find agni_description)/robots/$(arg R_EE)_includes.urdf.xacro" /> 
  <xacro:include filename="$(find agni_description)/robots/$(arg L_EE)_includes.urdf.xacro" /> 
  
  <xacro:include filename="$(find agni_description)/calibration/default_cal.xml"/>
  <xacro:include filename="$(find agni_description)/urdf/frame-half.urdf.xacro"/>
 
  <!-- 
  <xacro:frame-half prefix="$(arg ARM)" thickness="${cal_frame_thick}" width="${cal_frame_width}" depth="${cal_frame_depth}"
              height="${cal_frame_height}" tableHeight="${cal_frame_table_height}"/>

  arm and hand -->

  <xacro:if value="$(arg R)">
    <xacro:arm_ee parent="$(arg ARM)_frame" arm="$(arg ARM)" prefix="r" is_right="1" use_prefix="$(arg USE_PREFIX)" controller="false">
      <origin xyz="${cal_right_arm_x} ${cal_right_arm_y} ${cal_right_arm_z}"
      rpy="${cal_right_arm_roll} ${cal_right_arm_pitch} ${cal_right_arm_yaw}"/>
    </xacro:arm_ee>
  </xacro:if>
  <xacro:if value="$(arg L)">
    <xacro:arm_ee parent="$(arg ARM)_frame" arm="$(arg ARM)" prefix="l" is_right="0" use_prefix="$(arg USE_PREFIX)" controller="false">
      <origin xyz="${cal_left_arm_x} ${cal_left_arm_y} ${cal_left_arm_z}"
          rpy="${cal_left_arm_roll} ${cal_left_arm_pitch} ${cal_left_arm_yaw}"/>
    </xacro:arm_ee>
  </xacro:if>
  <xacro:if value="$(arg FLOBI)">
    <xacro:flobi prefix="" neutral="1" gender="0" parent="$(arg ARM)_frame" >
      <origin xyz="0 ${cal_right_arm_y} ${cal_right_arm_z+mount_triangle_length/2*sin60+0.01}" rpy="0 0 ${-M_PI/2}"/>
    </xacro:flobi>
 </xacro:if>

</robot>
