<?xml version="1.0"?>
<robot name="sdh" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find schunk_description)/urdf/sdh/sdh.urdf.xacro" />

  <xacro:macro name="schunk_hand" params="prefix:=''">
    <xacro:property name="prefix_" value="${'' if prefix=='' else prefix+'_'}"/>
    <link name="${prefix_}sdh_mount" />

     <!-- add cable adapter + female FCS part + red ring to schunk base frame -->
    <xacro:property name="cable_fcs_adapter_thickness" value="0.02" />
    <xacro:property name="cable_fcs_adapter_mass" value="0.030" />
    <joint name="${prefix_}cable_adapter_joint" type="fixed">
      <parent link="${prefix_}sdh_mount"/>
      <child link="${prefix_}cable_adapter_frame"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 ${cable_fcs_adapter_thickness}"/>
    </joint>
    <link name="${prefix_}cable_adapter_frame" >
      <!-- mass estimated not measured -->
      <xacro:cylinder_inertial length="${cable_fcs_adapter_thickness}" radius="0.038" mass="${cable_fcs_adapter_mass}">
        <origin xyz="0 0 ${-cable_fcs_adapter_thickness/2.0}"/>
      </xacro:cylinder_inertial> 
      <visual>
        <origin xyz="0 0 ${-cable_fcs_adapter_thickness/2.0}" rpy="0 0 0"/>
        <geometry>
           <cylinder radius="0.038" length="${cable_fcs_adapter_thickness}" />
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-cable_fcs_adapter_thickness/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.038" length="${cable_fcs_adapter_thickness}" />
        </geometry>
      </collision>
    </link>
    
    
    <xacro:call macro="schunk_sdh" parent="${prefix_}cable_adapter_frame" name="${prefix_}sdh" >
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:call>

    <gazebo>
      <plugin name="ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/${prefix}</robotNamespace>
        <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
      </plugin>
    </gazebo>

  </xacro:macro>
</robot>
