controller_list:
 - name: ra
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   joints: [ra_S1, ra_S2, ra_S3, ra_E1, ra_E2, ra_W1, ra_W2]

 - name: la
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   joints: [la_S1, la_S2, la_S3, la_E1, la_E2, la_W1, la_W2]
     
 - name: rh/rh_hand_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   joints: [rh_FFJ4, rh_FFJ3, rh_FFJ2, rh_FFJ1,
            rh_MFJ4, rh_MFJ3, rh_MFJ2, rh_MFJ1,
            rh_RFJ4, rh_RFJ3, rh_RFJ2, rh_RFJ1,
            rh_LFJ5, rh_LFJ4, rh_LFJ3, rh_LFJ2, rh_LFJ1,
            rh_THJ5, rh_THJ4, rh_THJ3, rh_THJ2, rh_THJ1,
            rh_WRJ2, rh_WRJ1]
   goal_tolerance:
     position: -1
     velocity: -1
     acceleration: -1
   path_tolerance:
     position: -1
     velocity: -1
     acceleration: -1
   goal_time_tolerance: 2.0

 - name: lh/lh_hand_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   joints: [lh_FFJ4, lh_FFJ3, lh_FFJ2, lh_FFJ1,
            lh_MFJ4, lh_MFJ3, lh_MFJ2, lh_MFJ1,
            lh_RFJ4, lh_RFJ3, lh_RFJ2, lh_RFJ1,
            lh_LFJ5, lh_LFJ4, lh_LFJ3, lh_LFJ2, lh_LFJ1,
            lh_THJ5, lh_THJ4, lh_THJ3, lh_THJ2, lh_THJ1,
            lh_WRJ2, lh_WRJ1]
   goal_tolerance:
     position: -1
     velocity: -1
     acceleration: -1
   path_tolerance:
     position: -1
     velocity: -1
     acceleration: -1
   goal_time_tolerance: 2.0
