# Max velocity limits available from LWR4+ arms

joint_limits:
  floka_neck_roll_joint:
    <<: &FLOKA_DEFAULTS
      has_velocity_limits: true
      max_velocity: 1.57
      has_acceleration_limits: false
      max_acceleration: 0
  floka_neck_tilt_joint:
    <<: *FLOKA_DEFAULTS
  floka_neck_pan_joint:
    <<: *FLOKA_DEFAULTS
  floka_eyes_right_ud_joint:
    <<: *FLOKA_DEFAULTS
  floka_eyes_left_ud_joint:
    <<: *FLOKA_DEFAULTS
  floka_eyes_left_lr_joint:
    <<: *FLOKA_DEFAULTS
  floka_eyes_right_lr_joint:
    <<: *FLOKA_DEFAULTS

  la_arm_0_joint:
    <<: &ARM_DEFAULTS
      has_velocity_limits: true
      has_acceleration_limits: false
      max_acceleration: 0
    max_velocity: 1.91986217719
  la_arm_1_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 1.91986217719
  la_arm_2_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 2.26892802759
  la_arm_3_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 2.26892802759
  la_arm_4_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 2.26892802759
  la_arm_5_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 3.14159265359
  la_arm_6_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 3.14159265359

  ra_arm_0_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 1.91986217719
  ra_arm_1_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 1.91986217719
  ra_arm_2_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 2.26892802759
  ra_arm_3_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 2.26892802759
  ra_arm_4_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 2.26892802759
  ra_arm_5_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 3.14159265359
  ra_arm_6_joint:
    <<: *ARM_DEFAULTS
    max_velocity: 3.14159265359

  lh_WRJ1:
    <<: &HAND_DEFAULTS
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: false
      max_acceleration: 0
  lh_WRJ2:
    <<: *HAND_DEFAULTS
  lh_THJ5:
    <<: *HAND_DEFAULTS
  lh_THJ4:
    <<: *HAND_DEFAULTS
  lh_THJ3:
    <<: *HAND_DEFAULTS
  lh_THJ2:
    <<: *HAND_DEFAULTS
  lh_THJ1:
    <<: *HAND_DEFAULTS
  lh_FFJ4:
    <<: *HAND_DEFAULTS
  lh_FFJ3:
    <<: *HAND_DEFAULTS
  lh_FFJ2:
    <<: *HAND_DEFAULTS
  lh_FFJ1:
    <<: *HAND_DEFAULTS
  lh_MFJ4:
    <<: *HAND_DEFAULTS
  lh_MFJ3:
    <<: *HAND_DEFAULTS
  lh_MFJ2:
    <<: *HAND_DEFAULTS
  lh_MFJ1:
    <<: *HAND_DEFAULTS
  lh_RFJ4:
    <<: *HAND_DEFAULTS
  lh_RFJ3:
    <<: *HAND_DEFAULTS
  lh_RFJ2:
    <<: *HAND_DEFAULTS
  lh_RFJ1:
    <<: *HAND_DEFAULTS
  lh_LFJ5:
    <<: *HAND_DEFAULTS
  lh_LFJ4:
    <<: *HAND_DEFAULTS
  lh_LFJ3:
    <<: *HAND_DEFAULTS
  lh_LFJ2:
    <<: *HAND_DEFAULTS
  lh_LFJ1:
    <<: *HAND_DEFAULTS

  rh_WRJ1:
    <<: *HAND_DEFAULTS
  rh_WRJ2:
    <<: *HAND_DEFAULTS
  rh_THJ5:
    <<: *HAND_DEFAULTS
  rh_THJ4:
    <<: *HAND_DEFAULTS
  rh_THJ3:
    <<: *HAND_DEFAULTS
  rh_THJ2:
    <<: *HAND_DEFAULTS
  rh_THJ1:
    <<: *HAND_DEFAULTS
  rh_FFJ4:
    <<: *HAND_DEFAULTS
  rh_FFJ3:
    <<: *HAND_DEFAULTS
  rh_FFJ2:
    <<: *HAND_DEFAULTS
  rh_FFJ1:
    <<: *HAND_DEFAULTS
  rh_MFJ4:
    <<: *HAND_DEFAULTS
  rh_MFJ3:
    <<: *HAND_DEFAULTS
  rh_MFJ2:
    <<: *HAND_DEFAULTS
  rh_MFJ1:
    <<: *HAND_DEFAULTS
  rh_RFJ4:
    <<: *HAND_DEFAULTS
  rh_RFJ3:
    <<: *HAND_DEFAULTS
  rh_RFJ2:
    <<: *HAND_DEFAULTS
  rh_RFJ1:
    <<: *HAND_DEFAULTS
  rh_LFJ5:
    <<: *HAND_DEFAULTS
  rh_LFJ4:
    <<: *HAND_DEFAULTS
  rh_LFJ3:
    <<: *HAND_DEFAULTS
  rh_LFJ2:
    <<: *HAND_DEFAULTS
  rh_LFJ1:
    <<: *HAND_DEFAULTS
