right_first_finger: &FINGER_DEFAULT
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  epsilon: 0.001
  orientation_vs_position: 0.1

right_middle_finger: *FINGER_DEFAULT
right_ring_finger: *FINGER_DEFAULT
right_little_finger: *FINGER_DEFAULT
right_thumb: *FINGER_DEFAULT

left_first_finger: *FINGER_DEFAULT
left_middle_finger: *FINGER_DEFAULT
left_ring_finger: *FINGER_DEFAULT
left_little_finger: *FINGER_DEFAULT
left_thumb: *FINGER_DEFAULT

left_arm: &ARM_DEFAULT
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  epsilon: 0.001
  orientation_vs_position: 0.1

right_arm: *ARM_DEFAULT
left_arm_palm: *ARM_DEFAULT
right_arm_palm: *ARM_DEFAULT
