controller_list:
 - name: ra/arm_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - ra_arm_0_joint
     - ra_arm_1_joint
     - ra_arm_2_joint
     - ra_arm_3_joint
     - ra_arm_4_joint
     - ra_arm_5_joint
     - ra_arm_6_joint
 - name: la/arm_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - la_arm_0_joint
     - la_arm_1_joint
     - la_arm_2_joint
     - la_arm_3_joint
     - la_arm_4_joint
     - la_arm_5_joint
     - la_arm_6_joint
 - name: rh/rh_hand_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - rh_FFJ4
     - rh_FFJ3
     - rh_FFJ2
     - rh_FFJ1
     - rh_LFJ5
     - rh_LFJ4
     - rh_LFJ3
     - rh_LFJ2
     - rh_LFJ1
     - rh_MFJ4
     - rh_MFJ3
     - rh_MFJ2
     - rh_MFJ1
     - rh_RFJ4
     - rh_RFJ3
     - rh_RFJ2
     - rh_RFJ1
     - rh_THJ5
     - rh_THJ4
     - rh_THJ3
     - rh_THJ2
     - rh_THJ1
     - rh_WRJ2
     - rh_WRJ1
 - name: lh/lh_hand_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - lh_FFJ4
     - lh_FFJ3
     - lh_FFJ2
     - lh_FFJ1
     - lh_LFJ5
     - lh_LFJ4
     - lh_LFJ3
     - lh_LFJ2
     - lh_LFJ1
     - lh_MFJ4
     - lh_MFJ3
     - lh_MFJ2
     - lh_MFJ1
     - lh_RFJ4
     - lh_RFJ3
     - lh_RFJ2
     - lh_RFJ1
     - lh_THJ5
     - lh_THJ4
     - lh_THJ3
     - lh_THJ2
     - lh_THJ1
     - lh_WRJ2
     - lh_WRJ1
