controller_list:
  - name: fake_ra_arm_controller
    joints:
      - ra_S1
      - ra_S2
      - ra_S3
      - ra_E1
      - ra_E2
      - ra_W1
      - ra_W2
  - name: fake_la_arm_controller
    joints:
      - la_S1
      - la_S2
      - la_S3
      - la_E1
      - la_E2
      - la_W1
      - la_W2
  - name: fake_ra_armhand_controller
    joints:
      - ra_S1
      - ra_S2
      - ra_S3
      - ra_E1
      - ra_E2
      - ra_W1
      - ra_W2
      - r_WRJ2
      - r_WRJ1
  - name: fake_la_armhand_controller
    joints:
      - la_S1
      - la_S2
      - la_S3
      - la_E1
      - la_E2
      - la_W1
      - la_W2
      - l_WRJ2
      - l_WRJ1
  - name: fake_la_hand_controller
    joints:
      - l_WRJ2
      - l_WRJ1
      - l_FFJ4
      - l_FFJ3
      - l_FFJ2
      - l_FFJ1
      - l_LFJ5
      - l_LFJ4
      - l_LFJ3
      - l_LFJ2
      - l_LFJ1
      - l_MFJ4
      - l_MFJ3
      - l_MFJ2
      - l_MFJ1
      - l_RFJ4
      - l_RFJ3
      - l_RFJ2
      - l_RFJ1
      - l_THJ5
      - l_THJ4
      - l_THJ3
      - l_THJ2
      - l_THJ1
  - name: fake_ra_hand_controller
    joints:
      - r_WRJ2
      - r_WRJ1
      - r_FFJ4
      - r_FFJ3
      - r_FFJ2
      - r_FFJ1
      - r_LFJ5
      - r_LFJ4
      - r_LFJ3
      - r_LFJ2
      - r_LFJ1
      - r_MFJ4
      - r_MFJ3
      - r_MFJ2
      - r_MFJ1
      - r_RFJ4
      - r_RFJ3
      - r_RFJ2
      - r_RFJ1
      - r_THJ5
      - r_THJ4
      - r_THJ3
      - r_THJ2
      - r_THJ1
  - name: fake_la_fingers_controller
    joints:
      - l_FFJ4
      - l_FFJ3
      - l_FFJ2
      - l_FFJ1
      - l_LFJ5
      - l_LFJ4
      - l_LFJ3
      - l_LFJ2
      - l_LFJ1
      - l_MFJ4
      - l_MFJ3
      - l_MFJ2
      - l_MFJ1
      - l_RFJ4
      - l_RFJ3
      - l_RFJ2
      - l_RFJ1
      - l_THJ5
      - l_THJ4
      - l_THJ3
      - l_THJ2
      - l_THJ1
  - name: fake_ra_fingers_controller
    joints:
      - r_FFJ4
      - r_FFJ3
      - r_FFJ2
      - r_FFJ1
      - r_LFJ5
      - r_LFJ4
      - r_LFJ3
      - r_LFJ2
      - r_LFJ1
      - r_MFJ4
      - r_MFJ3
      - r_MFJ2
      - r_MFJ1
      - r_RFJ4
      - r_RFJ3
      - r_RFJ2
      - r_RFJ1
      - r_THJ5
      - r_THJ4
      - r_THJ3
      - r_THJ2
      - r_THJ1
  - name: fake_upper_body_controller
    joints:
      - la_S1
      - la_S2
      - la_S3
      - la_E1
      - la_E2
      - la_W1
      - la_W2
      - l_WRJ2
      - l_WRJ1
      - l_FFJ4
      - l_FFJ3
      - l_FFJ2
      - l_FFJ1
      - l_LFJ5
      - l_LFJ4
      - l_LFJ3
      - l_LFJ2
      - l_LFJ1
      - l_MFJ4
      - l_MFJ3
      - l_MFJ2
      - l_MFJ1
      - l_RFJ4
      - l_RFJ3
      - l_RFJ2
      - l_RFJ1
      - l_THJ5
      - l_THJ4
      - l_THJ3
      - l_THJ2
      - l_THJ1
      - ra_S1
      - ra_S2
      - ra_S3
      - ra_E1
      - ra_E2
      - ra_W1
      - ra_W2
      - r_WRJ2
      - r_WRJ1
      - r_FFJ4
      - r_FFJ3
      - r_FFJ2
      - r_FFJ1
      - r_LFJ5
      - r_LFJ4
      - r_LFJ3
      - r_LFJ2
      - r_LFJ1
      - r_MFJ4
      - r_MFJ3
      - r_MFJ2
      - r_MFJ1
      - r_RFJ4
      - r_RFJ3
      - r_RFJ2
      - r_RFJ1
      - r_THJ5
      - r_THJ4
      - r_THJ3
      - r_THJ2
      - r_THJ1
  - name: fake_ra_first_finger_controller
    joints:
      - r_FFJ4
      - r_FFJ3
      - r_FFJ2
      - r_FFJ1
  - name: fake_ra_middle_finger_controller
    joints:
      - r_MFJ4
      - r_MFJ3
      - r_MFJ2
      - r_MFJ1
  - name: fake_ra_ring_finger_controller
    joints:
      - r_RFJ4
      - r_RFJ3
      - r_RFJ2
      - r_RFJ1
  - name: fake_ra_little_finger_controller
    joints:
      - r_LFJ5
      - r_LFJ4
      - r_LFJ3
      - r_LFJ2
      - r_LFJ1
  - name: fake_ra_thumb_controller
    joints:
      - r_THJ5
      - r_THJ4
      - r_THJ3
      - r_THJ2
      - r_THJ1
  - name: fake_la_first_finger_controller
    joints:
      - l_FFJ4
      - l_FFJ3
      - l_FFJ2
      - l_FFJ1
  - name: fake_la_middle_finger_controller
    joints:
      - l_MFJ4
      - l_MFJ3
      - l_MFJ2
      - l_MFJ1
  - name: fake_la_ring_finger_controller
    joints:
      - l_RFJ4
      - l_RFJ3
      - l_RFJ2
      - l_RFJ1
  - name: fake_la_little_finger_controller
    joints:
      - l_LFJ5
      - l_LFJ4
      - l_LFJ3
      - l_LFJ2
      - l_LFJ1
  - name: fake_la_thumb_controller
    joints:
      - l_THJ5
      - l_THJ4
      - l_THJ3
      - l_THJ2
      - l_THJ1
  - name: fake_both_hands_controller
    joints:
      - l_WRJ2
      - l_WRJ1
      - l_FFJ4
      - l_FFJ3
      - l_FFJ2
      - l_FFJ1
      - l_LFJ5
      - l_LFJ4
      - l_LFJ3
      - l_LFJ2
      - l_LFJ1
      - l_MFJ4
      - l_MFJ3
      - l_MFJ2
      - l_MFJ1
      - l_RFJ4
      - l_RFJ3
      - l_RFJ2
      - l_RFJ1
      - l_THJ5
      - l_THJ4
      - l_THJ3
      - l_THJ2
      - l_THJ1
      - r_WRJ2
      - r_WRJ1
      - r_FFJ4
      - r_FFJ3
      - r_FFJ2
      - r_FFJ1
      - r_LFJ5
      - r_LFJ4
      - r_LFJ3
      - r_LFJ2
      - r_LFJ1
      - r_MFJ4
      - r_MFJ3
      - r_MFJ2
      - r_MFJ1
      - r_RFJ4
      - r_RFJ3
      - r_RFJ2
      - r_RFJ1
      - r_THJ5
      - r_THJ4
      - r_THJ3
      - r_THJ2
      - r_THJ1
  - name: fake_both_armhand_controller
    joints:
      - la_S1
      - la_S2
      - la_S3
      - la_E1
      - la_E2
      - la_W1
      - la_W2
      - l_WRJ2
      - l_WRJ1
      - ra_S1
      - ra_S2
      - ra_S3
      - ra_E1
      - ra_E2
      - ra_W1
      - ra_W2
      - r_WRJ2
      - r_WRJ1
  - name: fake_both_arms_controller
    joints:
      - la_S1
      - la_S2
      - la_S3
      - la_E1
      - la_E2
      - la_W1
      - la_W2
      - ra_S1
      - ra_S2
      - ra_S3
      - ra_E1
      - ra_E2
      - ra_W1
      - ra_W2
