la_armhand:
  kinematics_solver: kdlh_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solverh_search_resolution: 0.005
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
ra_armhand:
  kinematics_solver: kdlh_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solverh_search_resolution: 0.005
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
ra_first_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
ra_middle_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
ra_ring_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
ra_little_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
ra_thumb:
  kinematics_solver: kdlh_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  position_only_ik: True
la_first_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
la_middle_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
la_ring_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
la_little_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  epsilon: 0.001
la_thumb:
  kinematics_solver: kdlh_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solverh_search_resolution: 0.001
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
  position_only_ik: True
la_arm:
  kinematics_solver: kdlh_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solverh_search_resolution: 0.005
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
ra_arm:
  kinematics_solver: kdlh_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solverh_search_resolution: 0.005
  kinematics_solverh_timeout: 0.005
  kinematics_solverh_attempts: 3
