joint_limits:
  ra_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  ra_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  ra_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  ra_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  ra_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  ra_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  ra_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #1.91986217719
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 1.0 # 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 1.0 #3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  la_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
