left_arm: &ARM_DEFAULT
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 1
  epsilon: 0.001
  tolerance/rotx: 0.1
  tolerance/roty: 0.1
  tolerance/rotz: 0.1
right_arm: *ARM_DEFAULT
