sh_lh_ffj0_mixed_position_velocity_controller:
  joint: lh_FFJ0
  position_pid:
    d: -0.5
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -8.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_ffj3_mixed_position_velocity_controller:
  joint: lh_FFJ3
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.3
    max_velocity: 1.5
    min_velocity: -1.5
    p: -5.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_ffj4_mixed_position_velocity_controller:
  joint: lh_FFJ4
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -4.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_lfj0_mixed_position_velocity_controller:
  joint: lh_LFJ0
  position_pid:
    d: -0.5
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -8.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_lfj3_mixed_position_velocity_controller:
  joint: lh_LFJ3
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.3
    max_velocity: 1.5
    min_velocity: -1.5
    p: -5.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_lfj4_mixed_position_velocity_controller:
  joint: lh_LFJ4
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -4.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_lfj5_mixed_position_velocity_controller:
  joint: lh_LFJ5
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -4.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_mfj0_mixed_position_velocity_controller:
  joint: lh_MFJ0
  position_pid:
    d: -0.5
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -8.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_mfj3_mixed_position_velocity_controller:
  joint: lh_MFJ3
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.3
    max_velocity: 1.5
    min_velocity: -1.5
    p: -5.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_mfj4_mixed_position_velocity_controller:
  joint: lh_MFJ4
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -4.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_rfj0_mixed_position_velocity_controller:
  joint: lh_RFJ0
  position_pid:
    d: -0.5
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -8.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_rfj3_mixed_position_velocity_controller:
  joint: lh_RFJ3
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.3
    max_velocity: 1.5
    min_velocity: -1.5
    p: -5.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_rfj4_mixed_position_velocity_controller:
  joint: lh_RFJ4
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -4.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_thj1_mixed_position_velocity_controller:
  joint: lh_THJ1
  position_pid:
    d: -0.5
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -8.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_thj2_mixed_position_velocity_controller:
  joint: lh_THJ2
  position_pid:
    d: -0.5
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -8.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_thj3_mixed_position_velocity_controller:
  joint: lh_THJ3
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -1.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_thj4_mixed_position_velocity_controller:
  joint: lh_THJ4
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_thj5_mixed_position_velocity_controller:
  joint: lh_THJ5
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 1.0
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 0.7
    max_force: 5.0
    p: 0.0

sh_lh_wrj1_mixed_position_velocity_controller:
  joint: lh_WRJ1
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -5.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 1.0
    max_force: 10.0
    p: 0.0

sh_lh_wrj2_mixed_position_velocity_controller:
  joint: lh_WRJ2
  position_pid:
    d: 0.0
    i: -0.2
    i_clamp: 0.5
    max_velocity: 1.5
    min_velocity: -1.5
    p: -3.0
    position_deadband: 0.0
  type: sr_mechanism_controllers/SrhMixedPositionVelocityJointController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 1.0
    max_force: 10.0
    p: -0.2


