default_joint_controller_type: sr_mechanism_controllers/SrhJointVelocityController
sh_lh_ffj0_velocity_controller:
  joint: lh_FFJ0
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_ffj3_velocity_controller:
  joint: lh_FFJ3
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_ffj4_velocity_controller:
  joint: lh_FFJ4
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_lfj0_velocity_controller:
  joint: lh_LFJ0
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_lfj3_velocity_controller:
  joint: lh_LFJ3
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_lfj4_velocity_controller:
  joint: lh_LFJ4
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_lfj5_velocity_controller:
  joint: lh_LFJ5
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_mfj0_velocity_controller:
  joint: lh_MFJ0
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_mfj3_velocity_controller:
  joint: lh_MFJ3
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_mfj4_velocity_controller:
  joint: lh_MFJ4
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_rfj0_velocity_controller:
  joint: lh_RFJ0
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_rfj3_velocity_controller:
  joint: lh_RFJ3
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 3.0
    p: -0.1

sh_lh_rfj4_velocity_controller:
  joint: lh_RFJ4
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -1.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_thj1_velocity_controller:
  joint: lh_THJ1
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_thj2_velocity_controller:
  joint: lh_THJ2
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.5
    i_clamp: 0.8
    max_force: 3.0
    p: 0.0

sh_lh_thj3_velocity_controller:
  joint: lh_THJ3
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_thj4_velocity_controller:
  joint: lh_THJ4
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 0.5
    max_force: 3.0
    p: 0.0

sh_lh_thj5_velocity_controller:
  joint: lh_THJ5
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 0.7
    max_force: 5.0
    p: 0.0

sh_lh_wrj1_velocity_controller:
  joint: lh_WRJ1
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 1.0
    max_force: 10.0
    p: 0.0

sh_lh_wrj2_velocity_controller:
  joint: lh_WRJ2
  type: sr_mechanism_controllers/SrhJointVelocityController
  pid:
    d: 0.0
    friction_deadband: 100.0
    i: -2.0
    i_clamp: 1.0
    max_force: 10.0
    p: -0.2


