sh_rh_ffj0_position_controller:
  joint: rh_FFJ0
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_ffj3_position_controller:
  joint: rh_FFJ3
  pid:
    d: 0.01
    i: 0.1
    i_clamp: 0.2
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_ffj4_position_controller:
  joint: rh_FFJ4
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.02
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj0_position_controller:
  joint: rh_LFJ0
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj3_position_controller:
  joint: rh_LFJ3
  pid:
    d: 0.01
    i: 0.1
    i_clamp: 0.2
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj4_position_controller:
  joint: rh_LFJ4
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.02
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj5_position_controller:
  joint: rh_LFJ5
  pid:
    d: 0.05
    i: 0.06
    i_clamp: 0.04
    p: 0.7
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_mfj0_position_controller:
  joint: rh_MFJ0
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_mfj3_position_controller:
  joint: rh_MFJ3
  pid:
    d: 0.01
    i: 0.1
    i_clamp: 0.2
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_mfj4_position_controller:
  joint: rh_MFJ4
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.02
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_rfj0_position_controller:
  joint: rh_RFJ0
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_rfj3_position_controller:
  joint: rh_RFJ3
  pid:
    d: 0.01
    i: 0.1
    i_clamp: 0.2
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_rfj4_position_controller:
  joint: rh_RFJ4
  pid:
    d: 0.0
    i: 0.02
    i_clamp: 0.01
    p: 0.02
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj1_position_controller:
  joint: rh_THJ1
  pid:
    d: 0.001
    i: 0.02
    i_clamp: 0.01
    p: 0.05
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj2_position_controller:
  joint: rh_THJ2
  pid:
    d: 0.007
    i: 0.03
    i_clamp: 0.02
    p: 0.07
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj3_position_controller:
  joint: rh_THJ3
  pid:
    d: 0.002
    i: 0.04
    i_clamp: 0.02
    p: 0.03
    position_deadband: 0.0
    max_force: 1.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj4_position_controller:
  joint: rh_THJ4
  pid:
    d: 0.002
    i: 0.02
    i_clamp: 0.04
    p: 0.1
    position_deadband: 0.0
    max_force: 2.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj5_position_controller:
  joint: rh_THJ5
  pid:
    d: 0.01
    i: 0.1
    i_clamp: 0.2
    p: 0.1
    position_deadband: 0.0
    max_force: 3.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_wrj1_position_controller:
  joint: rh_WRJ1
  pid:
    d: 2.0
    i: 10.0
    i_clamp: 4.0
    p: 15.0
    position_deadband: 0.0
    max_force: 5.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_wrj2_position_controller:
  joint: rh_WRJ2
  pid:
    d: 2.0
    i: 10.0
    i_clamp: 4.0
    p: 15.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController
