lh_hand_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - lh_sdh_knuckle_joint
    - lh_sdh_finger_12_joint
    - lh_sdh_finger_13_joint
    - lh_sdh_finger_21_joint
    - lh_sdh_finger_22_joint
    - lh_sdh_finger_23_joint
    - lh_sdh_thumb_2_joint
    - lh_sdh_thumb_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      lh_sdh_knuckle_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_finger_12_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_finger_13_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_finger_21_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_finger_22_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_finger_23_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_thumb_2_joint: {trajectory: 0.9, goal: 0.4}
      lh_sdh_thumb_3_joint: {trajectory: 0.9, goal: 0.4}
  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true
